apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app1
  labels:
    app: react-app1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-app1
  template:
    metadata:
      labels:
        app: react-app1
    spec:
      containers:
      - name: react-app1
        image: hornet55/reactjs-app:latest
        ports:
        - containerPort: 80
