name: deploy-on-minikube

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build Docker Image
        run: docker build -t hornet55/reactjs-app:latest .
      - name: Publish Image to Docker Hub
        run: docker push hornet55/reactjs-app:latest   

  deploy: 
    needs: build
    runs-on: self-hosted
    steps:
      - name: Start Minikube
        run: minikube start
      - name: Set Kubernetes Context to Minikube
        run: kubectl config use-context minikube
      - name: Pull Image from Docker Hub
        run: docker pull hornet55/reactjs-app:latest
      - name: Save Docker Image as tarball
        run: docker save hornet55/reactjs-app:latest -o reactjs-app.tar
      - name: Load Docker Image into Minikube
        run: minikube image load reactjs-app.tar
      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
      - name: Wait for Deployment to Roll Out
        run: kubectl rollout status deployment/react-app
      - name: Retrieve Minikube IP
        id: minikube_ip
        run: echo "MINIKUBE_IP=$(minikube ip)" >> $GITHUB_ENV
      - name: Output Minikube Access URL
        run: echo "Application is available at http://${{ env.MINIKUBE_IP }}:30000"
